version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=true
      - FLASK_ENV=development
      - MONGO_URI=mongodb://root:example@mongo:27017/taskdb?authSource=admin
      - DB_NAME=taskdb
      - SECRET_KEY=e5f3d78061dfca9b66f2bb9c1d8d091438848d355dae56339dcda83f8a78fa5760635c38380c3fee851c4c3476b0c44aa974dd4c63f23705e2e2c3250f37e41edfbb5c13459dff564afd4daad8b3af079fa0271bbcaa4fc77e1f72e18bca66fb598f3419b6a37fcc9ed45be878b6a290dc0a7566a0df5cc6f4d3bec7c735aebd
      - PYTHONPATH=/app/src
      - CORS_ALLOW_ORIGINS=http://localhost:3000
      - CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOW_HEADERS=Content-Type,Authorization

    volumes:
      - ./backend/src:/app/src
    command: flask run --host=0.0.0.0 --reload
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api/v1
      - REACT_APP_SECRET_KEY=e5f3d78061dfca9b66f2bb9c1d8d091438848d355dae56339dcda83f8a78fa5760635c38380c3fee851c4c3476b0c44aa974dd4c63f23705e2e2c3250f37e41edfbb5c13459dff564afd4daad8b3af079fa0271bbcaa4fc77e1f72e18bca66fb598f3419b6a37fcc9ed45be878b6a290dc0a7566a0df5cc6f4d3bec7c735aebd
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
      - ./frontend/public:/app/public
    command: npm start
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: taskdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
